// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC65dLZpgoWexyEVFMVfF3LlhaR64ofsbY',
    appId: '1:360032693198:web:79dc63933e43607fc1999f',
    messagingSenderId: '360032693198',
    projectId: 'provamobile2bim2025',
    authDomain: 'provamobile2bim2025.firebaseapp.com',
    storageBucket: 'provamobile2bim2025.firebasestorage.app',
    measurementId: 'G-2QW7JYV461',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBINX0n0keMKUreWIQKvktgwW0d28mVw4U',
    appId: '1:360032693198:android:4a20fadd026736fcc1999f',
    messagingSenderId: '360032693198',
    projectId: 'provamobile2bim2025',
    storageBucket: 'provamobile2bim2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh5xNarNZr5Be8qO1Apm-cdzA3tZor4Hg',
    appId: '1:360032693198:ios:12c557589eeb1b3dc1999f',
    messagingSenderId: '360032693198',
    projectId: 'provamobile2bim2025',
    storageBucket: 'provamobile2bim2025.firebasestorage.app',
    iosBundleId: 'com.example.notasapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh5xNarNZr5Be8qO1Apm-cdzA3tZor4Hg',
    appId: '1:360032693198:ios:12c557589eeb1b3dc1999f',
    messagingSenderId: '360032693198',
    projectId: 'provamobile2bim2025',
    storageBucket: 'provamobile2bim2025.firebasestorage.app',
    iosBundleId: 'com.example.notasapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC65dLZpgoWexyEVFMVfF3LlhaR64ofsbY',
    appId: '1:360032693198:web:d95a21180a69857ac1999f',
    messagingSenderId: '360032693198',
    projectId: 'provamobile2bim2025',
    authDomain: 'provamobile2bim2025.firebaseapp.com',
    storageBucket: 'provamobile2bim2025.firebasestorage.app',
    measurementId: 'G-L5RH8VKEJ5',
  );

}